defaults:
  - base_nontorch

_target_: darts.models.forecasting.xgboost.XGBModel
lags: 4
output_chunk_length: 12
lags_future_covariates:
  _target_: builtins.tuple
  _args_:
    - - ${model.lags}
      - ${model.output_chunk_length}
early_stopping_rounds: 5
