defaults:
  - elastic_net

lags: 11
output_chunk_length: 3
multi_models: False
model:
  l1_ratio: 0.9998692393656119
lags_future_covariates:
  _target_: builtins.tuple
  _args_:
    - - ${model.lags}
      - ${model.output_chunk_length}
