defaults:
  - elastic_net

lags: 4
output_chunk_length: 6
multi_models: False
model:
  l1_ratio: 0.3244398216072671
lags_future_covariates:
  _target_: builtins.tuple
  _args_:
    - - ${model.lags}
      - ${model.output_chunk_length}
