defaults:
  - base_torch

_target_: darts.models.forecasting.rnn_model.RNNModel
input_chunk_length: 8
output_chunk_length: 1
optimizer_cls:
  _target_: torch.optim.Adam
  _partial_: true
optimizer_kwargs:
  lr: 0.001
model: LSTM
hidden_dim: 12
training_length: ${eval:'${eval.kwargs.forecast_horizon} + ${model.input_chunk_length}'}
n_rnn_layers: 2
dropout: 0.0