# @package _global_

defaults:
  - base_torch

model:
  _target_: darts.models.forecasting.tcn_model.TCNModel
  input_chunk_length: 66
  kernel_size: 10
  num_filters: 11
  dilation_base: 3
  output_chunk_length: 18
  weight_norm: True
  num_layers: null # will set to get full history coverage
  loss_fn:
    _target_: torch.nn.MSELoss

# TCN does not accept future_covariates. Therefore, convert the future_covariates to past_covariates.
datamodule:
  data_variables:
    future_covariates: null
    past_covariates:
      - "Global_reactive_power"
      - "Voltage"
      - "Global_intensity"
      - "Sub_metering_1"
      - "Sub_metering_2"
      - "Sub_metering_3"
