defaults:
  - elastic_net

lags: 24
output_chunk_length: 12
multi_models: False
model:
  l1_ratio: 0.9711216246576823
lags_future_covariates:
  _target_: builtins.tuple
  _args_:
    - - ${model.lags}
      - ${model.output_chunk_length}
