defaults:
  - base_torch

_target_: darts.models.forecasting.tcn_model.TCNModel
input_chunk_length: 18
kernel_size: 3
num_filters: 5
output_chunk_length: 12
weight_norm: True
num_layers: null  # will set to get full history coverage
loss_fn:
    _target_: torch.nn.MSELoss






