defaults:
  - elastic_net

lags: 18
output_chunk_length: 1
multi_models: False
model:
  l1_ratio: 0.01
lags_future_covariates:
    _target_: builtins.tuple
    _args_:
      - - ${model.lags}
        - ${model.output_chunk_length}