# https://pytorch-lightning.readthedocs.io/en/latest/api/pytorch_lightning.callbacks.EarlyStopping.html

# Monitor a metric and stop training when it stops improving.
# Look at the above link for more detailed information.
prediction_plotter:
  _target_: src.callbacks.visualization.PredictionPlotterCallback
  val_plots_per_epoch: 3
  train_plots_per_epoch: null
  data_names: ${datamodule.data_variables}
  plot_covariates: True
