# @package _global_

defaults:
  - predict: default.yaml
  - paths: default.yaml
  - hydra: default.yaml
  # optional model (and datamodule) config for LocalForecastingModels which do not need to be trained first
  - optional model: none
  - optional datamodule: none
  - optional ensemble: default.yaml
  # optional local config for machine/user specific settings
  # it's optional since it doesn't need to exist and is excluded from version control
  - optional local: default.yaml
  - _self_

# passing model_dir is necessary for prediction. Configuration and model is loaded from this directory.
# model_dir is either a path relative to content root (e.g. logs/train/runs/YYYY-MM-DD_HH-MM-SS) or a full absolute path
model_dir: ???
# if the model is a pytorch model, one can provide the name of the checkpoint to load weights from.
ckpt: "best"

task_name: "predict"
tags: ["dev"]

extras:
  # disable output about accelerators and warnings about dataloaders
  disable_pytorch_lightning_output: True
# The config loaded from the log folder can be overridden by the supplying new configuration, e.g.:
#datamodule:
#  train_val_test_split: some new split
