# @package _global_

ensemble:
  _target_: src.models.ensemble_model.ReWTSEnsembleModel
  fit_forecast_horizon: ${oc.select:eval.kwargs.forecast_horizon,30}
  fit_weights_every: 1
  fit_stride: 1
  lookback_data_length: 150
  weight_threshold:
    1e-4 # Ensemble weights < weight_threshold are set to 0 in order to limit
    # amount of computations that have little impact

eval:
  kwargs:
    start: ${oc.select:ensemble.lookback_data_length,null}
